-- V1 — schema baseline.
--
-- What this is: the schema exactly as the JPA entities define it, captured at the moment
-- Flyway took over from `ddl-auto: update`. Everything after this point is an explicit,
-- reviewable, ordered change; this file is where that history starts.
--
-- How it was produced: NOT by dumping the development database. That database had been
-- built up by `update` over the project's life and still carried what `update` structurally
-- cannot remove — a `user` and a `company` table whose entities S07 deleted, a
-- `distribution_status` table superseded by `distribution_track`, and a `busincess_type`
-- column left behind by the spelling fix. Dumping it would have written all of that into
-- the baseline and made the residue permanent. Instead a scratch database was created,
-- `ddl-auto: create` was pointed at it so Hibernate materialised the schema from the
-- entities alone, and that was dumped. The result is 13 tables for 13 entities.
--
-- DO NOT EDIT THIS FILE. Flyway records a checksum per script; changing an applied script
-- makes every existing database fail validation. Schema changes are appended as V2, V3, ...
--
-- Column order is Hibernate's own (fixed-width types first, then the rest alphabetically),
-- kept as generated rather than tidied by hand — the point of a baseline is to match what
-- the ORM expects, and `ddl-auto: validate` is what checks that from here on.
--
-- Known oddity carried over deliberately: several columns default to the string 'LTD'.
-- That comes from hand-written `columnDefinition` values on the entities and predates this
-- refactor. It is preserved here because the baseline must describe what exists; changing
-- it is an entity decision for a later slice, made as its own migration.

CREATE TABLE IF NOT EXISTS `admin` (
  `create_at` varchar(255) DEFAULT NULL,
  `email` varchar(30) NOT NULL DEFAULT 'LTD',
  `id` varchar(255) NOT NULL,
  `password` varchar(100) NOT NULL DEFAULT 'LTD',
  `roles` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `commodity` (
  `count` int NOT NULL,
  `price` double NOT NULL,
  `create_at` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `update_at` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `distribution` (
  `from_lat` double NOT NULL,
  `from_lng` double NOT NULL,
  `status` int DEFAULT NULL,
  `to_lat` double NOT NULL,
  `to_lng` double NOT NULL,
  `urgent` bit(1) NOT NULL,
  `time` datetime(6) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `care` varchar(255) DEFAULT NULL,
  `did` varchar(255) DEFAULT NULL,
  `driver` varchar(255) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `number` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `vid` varchar(255) DEFAULT NULL,
  `wid` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `distribution_track` (
  `lat` double NOT NULL,
  `lng` double NOT NULL,
  `status` int DEFAULT NULL,
  `time` datetime(6) DEFAULT NULL,
  `dis_id` varchar(255) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `location` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `driver` (
  `driving` bit(1) NOT NULL,
  `address` varchar(255) DEFAULT NULL,
  `create_at` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `id_card` varchar(255) DEFAULT NULL,
  `license` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `score` varchar(255) DEFAULT NULL,
  `update_at` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `employee` (
  `address` varchar(255) DEFAULT NULL,
  `create_at` varchar(255) DEFAULT NULL,
  `department` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `id_card` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `update_at` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `inventory` (
  `count` int DEFAULT NULL,
  `cid` varchar(255) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `location` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `wid` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `inventory_record` (
  `count` int DEFAULT NULL,
  `type` int DEFAULT NULL,
  `cid` varchar(255) DEFAULT NULL,
  `create_at` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `wid` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `login_log` (
  `status` int DEFAULT NULL,
  `date` datetime(6) DEFAULT NULL,
  `browser` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `ip` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sale` (
  `pay` bit(1) NOT NULL,
  `price` double NOT NULL,
  `commodity` varchar(255) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `count` varchar(255) DEFAULT NULL,
  `create_at` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `number` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `system_log` (
  `success` tinyint(1) NOT NULL DEFAULT '1',
  `cost_ms` bigint DEFAULT NULL,
  `time` datetime(6) DEFAULT NULL,
  `account` varchar(255) DEFAULT NULL,
  `business_type` varchar(30) NOT NULL DEFAULT 'LTD',
  `id` varchar(255) NOT NULL,
  `ip` varchar(40) NOT NULL DEFAULT 'LTD',
  `method` varchar(100) NOT NULL DEFAULT 'LTD',
  `module` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `vehicle` (
  `driving` bit(1) NOT NULL,
  `create_at` varchar(255) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `number` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `warehouse` (
  `lat` double NOT NULL,
  `lng` double NOT NULL,
  `create_at` varchar(255) DEFAULT NULL,
  `id` varchar(255) NOT NULL,
  `location` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `principle` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

